---

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  delete-package-versions:
    name: Delete older containers
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.REGISTRYCLEANUP }}
          image-names: "mystation"
          tag-selection: untagged
          cut-off: 7d
          dry-run: true
